export const CORE_REDUCER = "CORE_REDUCER";
export const SET_ID_AND_SET_ROLE = "SET_ID_AND_SET_ROLE";
export const SET_ROLE = "SET_ROLE";
export const LOADING_FULLSCREEN = "LOADING_FULLSCREEN";
export const RESET_STATE = "RESET_STATE";
